-- PostgreSQL seed template
-- Replace {{PRICE_BOOK_ID}} and adjust column names to the actual Prisma schema.
INSERT INTO "PriceBookEntry"
("priceBookId","itemCode","itemName","unit","tier","unitPrice","category","note")
VALUES
('{PRICE_BOOK_ID}','PREP_001','Dọn dẹp, phá dỡ nhẹ hiện trạng','m2','standard',85000,'Chuẩn bị','Tham khảo BOQ thực tế; dùng cho cải tạo nhẹ'),
('{PRICE_BOOK_ID}','PREP_002','Vận chuyển phế thải trong phạm vi công trình','m3','standard',420000,'Chuẩn bị','Giá demo Hà Nội'),
('{PRICE_BOOK_ID}','PREP_004','Lán trại, điện nước tạm và an toàn công trường','gói','standard',18000000,'Chuẩn bị','Tạm tính theo gói nhà dân dụng'),
('{PRICE_BOOK_ID}','FND_001','Cọc BTCT 200x200 cung cấp tại công trình','m','standard',205000,'Móng','Neo theo BOQ nhà ở gia đình user cung cấp'),
('{PRICE_BOOK_ID}','FND_002','Ép cọc BTCT 200x200','m','standard',105000,'Móng','Quy đổi từ đơn giá ép cọc/100m'),
('{PRICE_BOOK_ID}','FND_003','Nối cọc BTCT 200x200','mối','standard',35000,'Móng','Neo theo BOQ thực tế'),
('{PRICE_BOOK_ID}','FND_004','Đập đầu cọc BTCT','cái','standard',120000,'Móng','Giá demo'),
('{PRICE_BOOK_ID}','FND_005','Đào đất móng bằng máy','m3','standard',95000,'Móng','Giá tổng hợp máy + nhân công'),
('{PRICE_BOOK_ID}','FND_006','Vận chuyển đất thừa ra khỏi công trình','m3','standard',220000,'Móng','Giá demo'),
('{PRICE_BOOK_ID}','FND_007','Bê tông lót móng M100','m3','standard',1620000,'Móng','Neo theo BOQ thực tế'),
('{PRICE_BOOK_ID}','FND_008','Bê tông móng thương phẩm M250','m3','standard',1720000,'Móng','Neo theo BOQ thực tế'),
('{PRICE_BOOK_ID}','FND_009','Cốt thép móng gia công lắp dựng','kg','standard',20000,'Móng','Quy đổi khoảng 20 triệu/tấn'),
('{PRICE_BOOK_ID}','FND_010','Ván khuôn móng ván phủ phim','m2','standard',175000,'Móng','Quy đổi từ BOQ'),
('{PRICE_BOOK_ID}','STR_001','Bê tông cột M250','m3','standard',1850000,'Kết cấu','Bao gồm bơm, hao hụt cơ bản'),
('{PRICE_BOOK_ID}','STR_002','Bê tông dầm M250','m3','standard',1850000,'Kết cấu','Bao gồm bơm, hao hụt cơ bản'),
('{PRICE_BOOK_ID}','STR_003','Bê tông sàn M250','m3','standard',1800000,'Kết cấu','Bao gồm bơm, hao hụt cơ bản'),
('{PRICE_BOOK_ID}','STR_004','Bê tông cầu thang M250','m3','standard',1950000,'Kết cấu','Thi công phức tạp hơn sàn'),
('{PRICE_BOOK_ID}','STR_005','Cốt thép cột gia công lắp dựng','kg','standard',20500,'Kết cấu','Giá tổng hợp vật tư + gia công'),
('{PRICE_BOOK_ID}','STR_006','Cốt thép dầm gia công lắp dựng','kg','standard',20500,'Kết cấu','Giá tổng hợp vật tư + gia công'),
('{PRICE_BOOK_ID}','STR_007','Cốt thép sàn gia công lắp dựng','kg','standard',20200,'Kết cấu','Giá tổng hợp vật tư + gia công'),
('{PRICE_BOOK_ID}','STR_009','Ván khuôn cột','m2','standard',230000,'Kết cấu','Giá demo'),
('{PRICE_BOOK_ID}','STR_010','Ván khuôn dầm','m2','standard',240000,'Kết cấu','Giá demo'),
('{PRICE_BOOK_ID}','STR_011','Ván khuôn sàn','m2','standard',190000,'Kết cấu','Giá demo'),
('{PRICE_BOOK_ID}','MAS_001','Xây tường gạch 110, vữa XM M75','m2','standard',285000,'Xây trát','Vật tư + nhân công'),
('{PRICE_BOOK_ID}','MAS_002','Xây tường gạch 220, vữa XM M75','m2','standard',465000,'Xây trát','Vật tư + nhân công'),
('{PRICE_BOOK_ID}','MAS_003','Xây tường rào gạch 110','m2','standard',305000,'Xây trát','Ngoài trời'),
('{PRICE_BOOK_ID}','MAS_004','Trát tường trong nhà dày 15mm','m2','standard',125000,'Xây trát','Vật tư + nhân công'),
('{PRICE_BOOK_ID}','MAS_005','Trát tường ngoài nhà dày 15mm','m2','standard',145000,'Xây trát','Có phụ phí ngoài trời'),
('{PRICE_BOOK_ID}','MAS_006','Trát trần bê tông','m2','standard',155000,'Xây trát','Giá demo'),
('{PRICE_BOOK_ID}','MAS_007','Cán nền vữa xi măng dày 20–30mm','m2','standard',115000,'Xây trát','Vật tư + nhân công'),
('{PRICE_BOOK_ID}','WPF_001','Chống thấm sàn WC 2 lớp','m2','standard',235000,'Chống thấm','Vật tư phổ thông + nhân công'),
('{PRICE_BOOK_ID}','WPF_002','Chống thấm ban công/logia','m2','standard',220000,'Chống thấm','Giá demo'),
('{PRICE_BOOK_ID}','WPF_003','Chống thấm mái bê tông','m2','standard',245000,'Chống thấm','Giá demo'),
('{PRICE_BOOK_ID}','WPF_004','Chống thấm bể nước/bể phốt','m2','standard',285000,'Chống thấm','Môi trường ẩm thường xuyên'),
('{PRICE_BOOK_ID}','WPF_005','Thử nước và xử lý cổ ống','điểm','standard',350000,'Chống thấm','Theo điểm'),
('{PRICE_BOOK_ID}','FIN_001','Bả matit tường trong nhà 2 lớp','m2','standard',55000,'Hoàn thiện','Vật tư + nhân công'),
('{PRICE_BOOK_ID}','FIN_002','Sơn nội thất hoàn thiện 1 lót 2 phủ','m2','standard',95000,'Hoàn thiện','Phân khúc tiêu chuẩn'),
('{PRICE_BOOK_ID}','FIN_003','Sơn ngoại thất hoàn thiện 1 lót 2 phủ','m2','standard',135000,'Hoàn thiện','Phân khúc tiêu chuẩn'),
('{PRICE_BOOK_ID}','FIN_004','Lát nền gạch 600x600 hoàn thiện','m2','standard',420000,'Hoàn thiện','Gồm gạch mức 220–260k/m2 + thi công'),
('{PRICE_BOOK_ID}','FIN_005','Lát nền gạch 800x800 hoàn thiện','m2','standard',520000,'Hoàn thiện','Gồm gạch mức trung bình + thi công'),
('{PRICE_BOOK_ID}','FIN_006','Ốp tường WC gạch 300x600','m2','standard',460000,'Hoàn thiện','Gồm gạch + keo/vữa + nhân công'),
('{PRICE_BOOK_ID}','FIN_007','Lát sàn WC chống trơn','m2','standard',470000,'Hoàn thiện','Gồm gạch + thi công'),
('{PRICE_BOOK_ID}','FIN_008','Ốp đá cầu thang granite','m2','standard',1250000,'Hoàn thiện','Đá tiêu chuẩn + lắp đặt'),
('{PRICE_BOOK_ID}','DOR_001','Cửa chính gỗ tự nhiên 4 cánh, phụ kiện đồng bộ','m2','standard',3300000,'Cửa','Neo theo BOQ thực tế'),
('{PRICE_BOOK_ID}','DOR_002','Cửa phòng composite 1 cánh, phụ kiện đồng bộ','m2','standard',2530000,'Cửa','Neo theo BOQ thực tế'),
('{PRICE_BOOK_ID}','DOR_003','Cửa WC composite chống nước','m2','standard',1980000,'Cửa','Neo theo BOQ thực tế'),
('{PRICE_BOOK_ID}','DOR_004','Cửa đi nhôm kính 1 cánh mở quay','m2','standard',2450000,'Cửa','PMA/Xingfa VN phân khúc trung bình'),
('{PRICE_BOOK_ID}','DOR_005','Cửa đi nhôm kính 2–4 cánh mở trượt','m2','standard',2350000,'Cửa','Neo theo BOQ thực tế'),
('{PRICE_BOOK_ID}','DOR_006','Cửa sổ nhôm kính mở quay/mở hất','m2','standard',1850000,'Cửa','Mức tham khảo thị trường 2026'),
('{PRICE_BOOK_ID}','DOR_007','Vách kính khung nhôm','m2','standard',1900000,'Cửa','Neo theo BOQ thực tế'),
('{PRICE_BOOK_ID}','DOR_008','Cửa cuốn khe thoáng kèm motor','m2','standard',2150000,'Cửa','Giá demo phân khúc tiêu chuẩn'),
('{PRICE_BOOK_ID}','CEI_001','Trần thạch cao phẳng khung chìm','m2','standard',235000,'Trần','Vật tư + nhân công'),
('{PRICE_BOOK_ID}','CEI_002','Trần thạch cao giật cấp đơn giản','m2','standard',315000,'Trần','Vật tư + nhân công'),
('{PRICE_BOOK_ID}','CEI_003','Trần thạch cao chống ẩm khu WC','m2','standard',285000,'Trần','Tấm chống ẩm'),
('{PRICE_BOOK_ID}','CEI_004','Sơn hoàn thiện trần thạch cao','m2','standard',85000,'Trần','1 lót 2 phủ'),
('{PRICE_BOOK_ID}','ELE_001','Đi dây điện âm tường cho ổ cắm','điểm','standard',520000,'Điện','Dây, ống, hộp âm, nhân công; chưa gồm mặt thiết bị'),
('{PRICE_BOOK_ID}','ELE_002','Đi dây điện âm tường cho công tắc/đèn','điểm','standard',420000,'Điện','Chưa gồm đèn'),
('{PRICE_BOOK_ID}','ELE_003','Ổ cắm đôi hoàn thiện','bộ','standard',280000,'Điện','Thiết bị phân khúc tiêu chuẩn'),
('{PRICE_BOOK_ID}','ELE_004','Công tắc đơn/đôi hoàn thiện','bộ','standard',220000,'Điện','Thiết bị phân khúc tiêu chuẩn'),
('{PRICE_BOOK_ID}','ELE_005','Đèn LED âm trần 7–9W hoàn thiện','bộ','standard',240000,'Điện','Thiết bị + lắp đặt'),
('{PRICE_BOOK_ID}','ELE_006','Tủ điện tổng gia đình','tủ','standard',6500000,'Điện','CB và phụ kiện mức tiêu chuẩn'),
('{PRICE_BOOK_ID}','ELE_007','Dây mạng LAN âm tường','điểm','standard',650000,'Điện','Cáp + ổ + nhân công'),
('{PRICE_BOOK_ID}','PLB_001','Điểm cấp nước lạnh PPR','điểm','standard',850000,'Cấp thoát nước','Ống, phụ kiện, nhân công'),
('{PRICE_BOOK_ID}','PLB_002','Điểm cấp nước nóng PPR','điểm','standard',950000,'Cấp thoát nước','Ống, phụ kiện, nhân công'),
('{PRICE_BOOK_ID}','PLB_003','Điểm thoát nước PVC D60–90','điểm','standard',980000,'Cấp thoát nước','Ống, phụ kiện, nhân công'),
('{PRICE_BOOK_ID}','PLB_004','Ống cấp nước trục đứng PPR','m','standard',320000,'Cấp thoát nước','Giá tổng hợp'),
('{PRICE_BOOK_ID}','PLB_005','Ống thoát trục đứng PVC D90–110','m','standard',420000,'Cấp thoát nước','Giá tổng hợp'),
('{PRICE_BOOK_ID}','PLB_006','Bể phốt BTCT hoàn thiện','m3','standard',4200000,'Cấp thoát nước','Tạm tính theo thể tích'),
('{PRICE_BOOK_ID}','PLB_007','Bể nước ngầm BTCT hoàn thiện','m3','standard',4800000,'Cấp thoát nước','Tạm tính theo thể tích'),
('{PRICE_BOOK_ID}','SAN_001','Bồn cầu 2 khối tiêu chuẩn','bộ','standard',4200000,'Thiết bị vệ sinh','INAX/Viglacera hoặc tương đương'),
('{PRICE_BOOK_ID}','SAN_002','Lavabo treo bàn/treo tường tiêu chuẩn','bộ','standard',1800000,'Thiết bị vệ sinh','Chưa gồm tủ'),
('{PRICE_BOOK_ID}','SAN_003','Vòi lavabo nóng lạnh','bộ','standard',1450000,'Thiết bị vệ sinh','Phân khúc tiêu chuẩn'),
('{PRICE_BOOK_ID}','SAN_004','Sen tắm nóng lạnh','bộ','standard',2600000,'Thiết bị vệ sinh','Phân khúc tiêu chuẩn'),
('{PRICE_BOOK_ID}','SAN_005','Vòi xịt vệ sinh','bộ','standard',450000,'Thiết bị vệ sinh','Thiết bị + lắp'),
('{PRICE_BOOK_ID}','SAN_006','Bộ phụ kiện WC cơ bản','bộ','standard',1200000,'Thiết bị vệ sinh','Gương, lô giấy, móc, thanh khăn'),
('{PRICE_BOOK_ID}','ROF_001','Mái tôn chống nóng khung thép hộp','m2','standard',780000,'Mái & ngoài nhà','Tôn + khung + lắp dựng'),
('{PRICE_BOOK_ID}','ROF_002','Mái ngói trên hệ khung thép','m2','standard',1450000,'Mái & ngoài nhà','Ngói + khung + phụ kiện'),
('{PRICE_BOOK_ID}','ROF_003','Lát sân gạch chống trơn','m2','standard',390000,'Mái & ngoài nhà','Gạch + nền + nhân công'),
('{PRICE_BOOK_ID}','ROF_004','Cổng sắt hộp sơn tĩnh điện','m2','standard',1850000,'Mái & ngoài nhà','Giá demo'),
('{PRICE_BOOK_ID}','ROF_006','Thoát nước mái, máng và ống đứng','m','standard',320000,'Mái & ngoài nhà','Tôn/inox/PVC tùy vị trí');
